### ISSUE TITLE
可以註冊到 Azure Notification Hub 上，但無法接收到測試推播

### ISSUE THREAD

**Issue by vulcanlee** [xyfoo/Baidu.Android.PushService#1]
您好

我有建立一個百度雲推送應用
根據您提供的範例專案，我可以成功執行到 `SendRegistrationToAppServer` 這個方法，並且也成功地向我自己建立的 Azure Notification Hub 註冊成功。

不過，當我利用 Azure Notification Hub 上提供的發送百度測試推播功能，在該測試網頁下方的結果中，有看到成功的推送出我剛剛註冊的裝置。

我對於 OnMessage, OnNotificationArrived, OnNotificationClicked 方法中設下中斷點，卻發現到這幾個方法都沒有被觸發。

請問，您是否知道問題可能在哪裡呢？我現在是在台灣，使用台灣的網路是否可以正常使用百度雲推送呢？

**Comment by vulcanlee** [comment]
若有需要，我可以提供我的測試專案原始碼給您

**Comment by vulcanlee** [comment]
@xyfoo 

我有將整個執行過程錄製下來，您可以透過 [影片連結](https://www.screencast.com/t/pfYEbqxM) 看到我這裡的執行狀況

**Comment by xyfoo** [comment]
我中文造诣欠佳，若中英有别，请以英文作准。

---

> 我對於 OnMessage, OnNotificationArrived, OnNotificationClicked 方法中設下中斷點，卻發現到這幾個方法都沒有被觸發

百度 SDK在debugger连接时不大可靠 (我没去找出原因所在）。
你可试试看直接deploy去你手机/emulator，再重新推送。

My experience is that the SDK doesn't work reliably when the VS debugger is attached (I have no idea why). But it will work when you deploy directly to the device (Project > Deploy).

> 我現在是在台灣，使用台灣的網路是否可以正常使用百度雲推送呢？

我只在马来西亚的网络做过测试，没问题。
那我猜台湾应该也不会有问题呱。

It works ok for me in Malaysia, so I suppose it should work for Taiwan network too.

---

如果还是不行，那我建议你下载百度提供的debug APK，以做些简单的检测。

If that still doesn't work, you can try to install the debugging tools provided by Baidu, to help to diagnose what may have gone wrong.

http://push.baidu.com/static/downloads/DetectToolsForDeveloper.apk

**Comment by vulcanlee** [comment]
@xyfoo 

感謝您的提醒，我來測試看看

**Comment by vulcanlee** [comment]
@xyfoo 

非常感謝您的幫忙與提供這麼好用的套件，根據您的建議，我手動 deploy 到手機上，接著直接開啟我的測試 App，可以正常收到 Push Notification
